FilmsCatalog/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FilmsCatalog.Data;
using FilmsCatalog.Services.Interfaces;
using FilmsCatalog.Models;
using FilmsCatalog.Extensions;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.Extensions.Logging;

namespace FilmsCatalog.Controllers
{
    [Route("films")]
    public class FilmsController : Controller
    {       
        private readonly IFilmService _filmService;
        private readonly IGenreService _genreService;        
        private readonly  IWebHostEnvironment _appEnvironment;
        private readonly ILogger<AccountController> _logger;

        public FilmsController(
            ApplicationDbContext context,            
            IFilmService filmService,
            IGenreService genreService,
            IWebHostEnvironment appEnvironment,
            ILogger<AccountController> logger)
        {                   
            _filmService = filmService;
            _genreService = genreService;
            _appEnvironment = appEnvironment;
            _logger = logger;
        }

        // GET: Films
        [HttpGet("{pageSize:int}/{pageNumber:int}",Name ="filmCatalog")]
        public async Task<IActionResult> Index(PaginationFilter filter)
        {            
            var films = await _filmService.GetAllFilmsAsync(filter.PageNumber, filter.PageSize);
            var total = await _filmService.FilmsCount();
            var page = new PagedViewModel<IEnumerable<FilmsCatalog.Models.FilmShortViewModel>>(films, filter.PageNumber, filter.PageSize, total);
            
            return View("index", page);
        }
        

        [Authorize]
        [HttpGet("list/{pageSize:int}/{pageNumber:int}", Name = "filmList")]
        public async Task<IActionResult> List(PaginationFilter filter)
        {        
            
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null) return Forbid();

            var films = await _filmService.GetFilmsByUserIdAsync(userId, filter.PageNumber, filter.PageSize);
            var total = await _filmService.FilmsCountByUserId(userId);
            var page = new PagedViewModel<IEnumerable<FilmsCatalog.Models.FilmShortViewModel>>(films, filter.PageNumber, filter.PageSize, total);
            return View("list", page);
        }

        // GET: Films/Details/5
        [HttpGet("{id:guid}", Name ="filmDetails")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var film = await _filmService.GetFilmByIdAsync(id.Value);            
            if (film == null) return NotFound();           

            return View(film);
        }


        // GET: Films/Create
        [Authorize]
        [HttpGet("create",Name ="filmCreate")]
        public IActionResult Create()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);           
            if (userId == null) return Forbid();

            ViewData["AutherId"] = userId;           
            return View();
        }

        // POST: Films/Create       
        [HttpPost("create", Name ="filmCreatePost")]
        [Authorize]
        [ValidateAntiForgeryToken]        
        public async Task<IActionResult> Create(FilmCreateEditViewModel newFilm)
        {                      
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null) return Forbid();
            if (newFilm == null) return BadRequest(); 

            if (ModelState.IsValid)
            {               
               var result = await _filmService.AddNewFilmAsync(newFilm, userId);
                _logger.LogInformation($"Film with id={newFilm.Id} was succesfully created");
                return RedirectToAction(nameof(Index), new { pageSize = 5, pageNumber = 1 }); ;
            }
           
            ViewData["AutherId"] = userId;
            return View(newFilm);
        }

        // GET: Films/Edit/5
        [Authorize]
        [HttpGet("edit/{id:guid}", Name = "filmEdit")]
        public async Task<IActionResult> Edit(Guid? id)
        {           
            if (id == null)
            {
                return BadRequest();
            }
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);            
            if (userId == null ) return Forbid();
            
            var film = await _filmService.GetForEditFilmByIdAsync(id.Value);
            if (film == null)
            {
                return NotFound();
            }
            if (userId != film.AutherId) return Forbid();

            ViewData["AutherId"] = userId;
            return View(film);
        }

        // POST: Films/Edit/5        
        [HttpPost("edit/{id:guid}", Name = "filmEditPost")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, FilmCreateEditViewModel film)
        {
            if (id != film.Id)
            {
                return NotFound();
            }
            if (film == null) return BadRequest();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);            
            if (userId == null) return Forbid();
            if (userId != film.AutherId) return Forbid();

            if (ModelState.IsValid)
            {
                var result = await _filmService.UpdateFilmAsync(id, film, userId);
                _logger.LogInformation($"Film with id={id} was succesfully edited");
                return Redirect(Url.Action(nameof(Details),  new { Id = id })) ;
            }

            ViewData["AutherId"] = userId;
            return View(film);
        }

        // GET: Films/Delete/5
        [Authorize]
        [HttpGet("delete/{id:guid}", Name = "filmDelete")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return BadRequest();
            }           
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null) return Forbid();
            var film = await _filmService.GetShortFilmByIdAsync(id.Value);
            if (userId != film.AutherId) return Forbid();
            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost("delete/{id:guid}", Name = "filmDeleteConfirmed")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);            
            if (userId == null) return Forbid();

            var film = await _filmService.GetShortFilmByIdAsync(id);
            if (film == null) return NotFound();
            if (userId != film.AutherId) return Forbid();

            var result = await _filmService.RemoveFilmAsync(id, userId);
            _logger.LogInformation($"Film with id={id} was succesfully deleted");
            return RedirectToAction(nameof(Index),new { pageSize=5, pageNumber=1 });
        }


        // GET: Films/AddFile/5
        [Authorize]
        [HttpGet("addposter/{id:guid}", Name = "filmAddPoster")]
        public async Task<IActionResult> AddFile(Guid? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);            
            if (userId == null) return Forbid();
            var film = await _filmService.GetForEditFilmByIdAsync(id.Value);
            if (film == null) return NotFound();
            if (userId != film.AutherId) return Forbid();

            ViewData["AutherId"] = userId;
            return View(film);
        }

        // POST: Films/AddFile/5        
        [HttpPost("addposter/{id:guid}", Name = "filmAddPosterPost")]
        [Authorize]
        [ValidateAntiForgeryToken]       
        public async Task<IActionResult> AddFile(Guid id, IFormFile uploadedFile, string slug)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);            
            if (userId == null) return Forbid();
            var film = await _filmService.GetForEditFilmByIdAsync(id);
            if (film == null) return NotFound();
            if (userId != film.AutherId) return Forbid();

            if (uploadedFile != null)
            {
                string imagePath = _appEnvironment.WebRootPath + @"\images\";
                string subFolder = slug.Substring(0, 1);
                DirectoryInfo dirInfo = new DirectoryInfo(imagePath + subFolder);
                if (!dirInfo.Exists)
                {
                    dirInfo.Create();
                    _logger.LogInformation($"Folder {imagePath + subFolder} was succesfully created");
                }

                string path = subFolder + @"\" + slug + uploadedFile.FileName.Substring(uploadedFile.FileName.Length-5);                
                using (var fileStream = new FileStream(imagePath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }               
                film.PosterImagePath = path;
                var result = await _filmService.UpdateFilmAsync(id, film, userId);
                _logger.LogInformation($"Poster for film with id={id} was succesfully uploaded");
            } 
            return Redirect(Url.Action(nameof(Details), new { Id = id }));
        }         
    }
}

FilmsCatalog/Views/Films/AddFile.cshtml
@model FilmsCatalog.Models.FilmCreateEditViewModel
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}
<section class=" section">
    <div class="container">
        <h1>@Model.Title</h1>
        <h4>Редактирование постера</h4>
        <hr />
        <div class="row form-group">
            <div class="col-lg-5 card thumb-content">
                <img class="card-img-top img-fluid" src="~/images/@Model.PosterImagePath" alt="@Model.Title">
            </div>
            <div class="col-3">
                <label asp-for="PosterImagePath" class="control-label"></label>
            </div>
            <div class="col-9">
                <br />
                <input asp-for="PosterImagePath" class="form-control" />
                <span asp-validation-for="PosterImagePath" class="text-danger"></span>
            </div>
        </div>


        <div class="row form-group">
            <form asp-action="AddFile" asp-controller="Films" asp-route-id="@(Model.Id)" method="post" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="Slug" />
                <input type="hidden" asp-for="AutherId" />
                <div>
                    <input type="file" class="btn btn-primary" name="uploadedFile" required />

                    <br /><br />
                    <input type="text" autocomplete="off" placeholder="Enter File Name" name="description" value="@Model.Slug" />

                    <input type="submit" class="btn btn-primary" value="Загрузить" />
                </div>
            </form>
            </div>
        </div>
</section>

FilmsCatalog/Views/Films/Create.cshtml
@model FilmsCatalog.Models.FilmCreateEditViewModel

@{
    ViewBag.Title = "Добавление нового фильма";
    ViewBag.Description = "Добавление нового фильма";
    ViewBag.Keywords = "Добавление нового фильма";
}

<section class=" section">
    <div class="container">
        <h1>Добавление нового фильма</h1>
        <hr />
        <div class="row">
            <div class="col-md-7">
                <form asp-action="Create">
                    <input type="hidden" asp-for="AutherId" />
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Annotation" class="control-label"></label>
                        <textarea asp-for="Annotation" class="form-control"></textarea>
                        <span asp-validation-for="Annotation" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Year" class="control-label"></label>
                        <input asp-for="Year" class="form-control" />
                        <span asp-validation-for="Year" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Director" class="control-label"></label>
                        <input asp-for="Director" class="form-control" />
                        <span asp-validation-for="Director" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Duration" class="control-label"></label>
                        <input asp-for="Duration" class="form-control" />
                        <span asp-validation-for="Duration" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TrailerUrl" class="control-label"></label>
                        <input asp-for="TrailerUrl" class="form-control" />
                        <span asp-validation-for="TrailerUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Slug" class="control-label"></label>
                        <input asp-for="Slug" class="form-control" />
                        <span asp-validation-for="Slug" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MetaTitle" class="control-label"></label>
                        <input asp-for="MetaTitle" class="form-control" />
                        <span asp-validation-for="MetaTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MetaDescription" class="control-label"></label>
                        <input asp-for="MetaDescription" class="form-control" />
                        <span asp-validation-for="MetaDescription" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MetaKeywords" class="control-label"></label>
                        <input asp-for="MetaKeywords" class="form-control" />
                        <span asp-validation-for="MetaKeywords" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a  asp-route="filmCatalog" asp-route-pageSize="5" asp-route-pageNumber="1">В каталог</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }
    </div>
</section>

FilmsCatalog/Views/Films/Delete.cshtml
@model FilmsCatalog.Models.FilmShortViewModel

@{
    ViewBag.Title = Model.Title;
    ViewBag.Description = Model.Title;
    ViewBag.Keywords = Model.Title;

}


<section class=" section">
    <div class="container">
        <h1>@Model.Title</h1>        

        <h3>Вы действительно хотите удалить фильм?</h3>
        <div>
            <hr />
            <div class="col-lg-3 card thumb-content">
                <img class="card-img-top img-fluid" src="~/images/@Model.PosterImagePath" alt="@Model.Title">
            </div>
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Title)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Title)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Annotation)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Annotation)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Year)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Year)
                </dd> 
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="AutherId" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a  asp-route="filmCatalog" asp-route-pageSize="5" asp-route-pageNumber="1">В каталог</a>
            </form>
        </div>
    </div>
</section>

FilmsCatalog/Views/Films/Details.cshtml
@model FilmsCatalog.Models.FilmFullViewModel

@{    
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords =Model.MetaKeywords;

}

<section class=" section">   
    <div class="container">
        <h1>@Model.Title</h1>
        <div class="row">
            <div class="col-lg-4 card thumb-content">
                <img class="card-img-top img-fluid" src="~/images/@Model.PosterImagePath" alt="@Model.Title">
            </div>
            <div class="col-lg-6 ">
                <h4>Описание фильма</h4>
                <hr />
                @Html.DisplayFor(model => model.Description)
                <br />
                <br />
                <dl class="row">
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.Year)
                    </dt>
                    <dd class="col-sm-6">
                        @Html.DisplayFor(model => model.Year)
                    </dd>
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.Director)
                    </dt>
                    <dd class="col-sm-6">
                        @Html.DisplayFor(model => model.Director)
                    </dd>
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.Duration)
                    </dt>
                    <dd class="col-sm-6">
                        @Html.DisplayFor(model => model.Duration)
                    </dd>
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.TrailerUrl)
                    </dt>
                    <dd class="col-sm-6">
                        <a href="@Model.TrailerUrl">Ссылка</a>
                    </dd>
                </dl>
            </div>
            <div>
                <a asp-action="Edit" asp-route-id="@Model.Id">Изменить</a> |
                <a   asp-route="filmCatalog" asp-route-pageSize="5" asp-route-pageNumber="1">В каталог</a>
            </div>
        </div>
        </div>
</section>

FilmsCatalog/Views/Films/Edit.cshtml
@model FilmsCatalog.Models.FilmCreateEditViewModel

@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;

}

<section class=" section">
    <div class="container">
        <h1>@Model.Title</h1>        

        <h4>Редактирование</h4>
        <hr />
        <div class="row">
            <div class="col-md-12">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="AutherId" />
                    <div class="row form-group">
                        <div class="col-3">
                            <label asp-for="Title" class="control-label"></label>
                        </div>
                        <div class="col-9">
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>


                    <div class="row form-group">
                        <div class="col-lg-4 card thumb-content">
                            <img class="card-img-top img-fluid" src="~/images/@Model.PosterImagePath" alt="@Model.Title">
                        </div>
                        <div class="col-3">
                            <label asp-for="PosterImagePath" class="control-label"></label>

                            <div>  <a class="btn btn-primary" asp-action="AddFile" asp-route-id="@Model.Id">Загрузить</a></div>
                        </div>
                        <div class="col-9">
                            <br />
                            <input asp-for="PosterImagePath" class="form-control" />
                            <span asp-validation-for="PosterImagePath" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label asp-for="Annotation" class="control-label"></label>
                        </div>
                        <div class="col-9">
                            <textarea asp-for="Annotation" class="form-control"></textarea>
                            <span asp-validation-for="Annotation" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label asp-for="Description" class="control-label"></label>
                        </div>
                        <div class="col-9">
                            <textarea asp-for="Description" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label asp-for="Year" class="control-label"></label>
                        </div>
                        <div class="col-9">

                            <input asp-for="Year" class="form-control" />
                            <span asp-validation-for="Year" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label asp-for="Director" class="control-label"></label>
                        </div>
                        <div class="col-9">
                            <input asp-for="Director" class="form-control" />
                            <span asp-validation-for="Director" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label asp-for="Duration" class="control-label"></label>
                        </div>
                        <div class="col-9">
                            <input asp-for="Duration" class="form-control" />
                            <span asp-validation-for="Duration" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label asp-for="TrailerUrl" class="control-label"></label>
                        </div>
                        <div class="col-9">
                            <input asp-for="TrailerUrl" class="form-control" />
                            <span asp-validation-for="TrailerUrl" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label asp-for="Slug" class="control-label"></label>
                        </div>
                        <div class="col-9">
                            <input asp-for="Slug" class="form-control" />
                            <span asp-validation-for="Slug" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label asp-for="MetaTitle" class="control-label"></label>
                        </div>
                        <div class="col-9">
                            <input asp-for="MetaTitle" class="form-control" />
                            <span asp-validation-for="MetaTitle" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label asp-for="MetaDescription" class="control-label"></label>
                        </div>
                        <div class="col-9">
                            <input asp-for="MetaDescription" class="form-control" />
                            <span asp-validation-for="MetaDescription" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label asp-for="MetaKeywords" class="control-label"></label>
                        </div>
                        <div class="col-9">
                            <input asp-for="MetaKeywords" class="form-control" />
                            <span asp-validation-for="MetaKeywords" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Сохранить" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a   asp-route="filmCatalog" asp-route-pageSize="5" asp-route-pageNumber="1">В каталог</a>
        </div>
        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }

    </div>
</section>

FilmsCatalog/Views/Films/Index.cshtml
@model PagedViewModel<IEnumerable<FilmsCatalog.Models.FilmShortViewModel>>

@{
    ViewBag.Title = "Каталог фильмов";
    ViewBag.Description = "Каталог фильмов";
    ViewBag.Keywords = "Каталог фильмов";
}

<section class="popular-deals section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title">
                    <h2>Все фильмы</h2>
                </div>
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model.Data)
            {
                var annotation = item.Annotation.Length < 80 ? item.Annotation : item.Annotation.Substring(0, 80);
                <!-- offer  -->
                <div class="col-sm-12 col-lg-4">
                    <!-- product card -->
                    <div class="category-block">
                        <div class="">
                            <div class="thumb-content">
                                <a asp-controller="Films" asp-action="Details" asp-route-id="@item.Id">
                                    <img class="card-img-top img-fluid" src="~/images/@item.PosterImagePath" alt="@item.Title">
                                </a>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title"><a asp-controller="Films" asp-action="Details" asp-route-id="@item.Id">@item.Title</a></h4>
                                <ul class="list-inline product-meta">
                                    <li class="list-inline-item">
                                        <a href=""><i class="fa fa-folder-open-o"></i>@item.Genres?.FirstOrDefault()</a>
                                    </li>
                                    <li class="list-inline-item">@item?.Year</li>
                                </ul>
                                <p class="card-text">@annotation</p>

                                <div class="product-ratings">
                                    <ul class="list-inline">
                                        <li class="list-inline-item selected"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item selected"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item selected"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item selected"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item"><i class="fa fa-star"></i></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        
            @if (Model.HasPreviousPage)
            {
                <a asp-action="Index"
                   asp-route-pageNumber="1"
                   asp-route-pageSize="@(Model.PageSize)"
                   class="btn btn-outline-dark">
                    <i class="glyphicon glyphicon-chevron-left"></i>
                    Начало
                </a>           
                <a asp-action="Index"
                   asp-route-pageNumber="@(Model.PageNumber - 1)"
                   asp-route-pageSize="@(Model.PageSize)"
                   class="btn btn-outline-dark">
                    <i class="glyphicon glyphicon-chevron-left"></i>
                    Назад
                </a>
            }
            @if (Model.HasNextPage)
            {
                <a asp-action="Index"
                   asp-route-pageNumber="@(Model.PageNumber + 1)"
                   asp-route-pageSize="@(Model.PageSize)"
                   class="btn btn-outline-dark">
                    <i class="glyphicon glyphicon-chevron-right"></i>
                    Вперед

                </a>
                <a asp-action="Index"
                   asp-route-pageNumber="@(Model.TotalPages)"
                   asp-route-pageSize="@(Model.PageSize)"
                   class="btn btn-outline-dark">
                    <i class="glyphicon glyphicon-chevron-right"></i>
                    Конец

                </a>
            }
       

    </div>
</section>